### ISSUE TITLE
Unavailable to get profile after 2015-01-13

### ISSUE THREAD

**Issue by dodo0822** [HSNU-CNMC/query#1]
The original system seemed to be updated and the id of the name field was removed. Now we should capture data by `class="Chap"`.

**Comment by andy0130tw** [comment]
It's glad to see that the system has been updated. Nothing new, though.

I suggest directly search name over:
http://grades.hs.ntnu.edu.tw/online/student/selection_look_over_data.asp?look_over=right_below
This should be much more stable since it comes in tabular form.

**Comment by dodo0822** [comment]
I will switch to using that page. Student ID and can also be retrieved there. Thanks!

**Comment by dodo0822** [comment]
Done!
